### ISSUE TITLE
docker GPU issues

### ISSUE THREAD

**Issue by snufas** [JeffreyCA/spleeter-web#342]
Hello have some issues running docker GPU, could be my fault entirely...

root@DESKTOP-7A6UGRU:/home/snufas/github_projects/spleeter-web# docker-compose -f docker-compose.gpu.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up
[+] Running 0/0
 ⠋ Container spleeter-web-celery-slow-1                    Creating                                                0.0s
 ⠋ Container ad67933017a4_ad67933017a4_spleeter-web-api-1  Recreate                                                0.0s
 ⠋ Container spleeter-web-celery-fast-1                    Creating                                                0.0s
Error response from daemon: Unknown runtime specified nvidia

Please note that other docker projects with gpu works just fine...
any advice what to do to solve this issue?
Also I am trying to run this on wsl2 if that makes any difference.
Thanks for help.

**Comment by JeffreyCA** [comment]
Hi, thanks for reporting this issue.

It looks like it may have to do with a legacy setting in the Docker Compose file. Can you try replacing the contents of `docker-compose.gpu.yml` with the following, then run the `up` command?

```yml
x-celery-env: &celery-env
  - DJANGO_SETTINGS_MODULE=django_react.settings_docker
  - CELERY_BROKER_URL=redis://redis:6379/0
  - CELERY_RESULT_BACKEND=redis://redis:6379/0
  - CPU_SEPARATION=0
  - CELERY_FAST_QUEUE_CONCURRENCY=${CELERY_FAST_QUEUE_CONCURRENCY:-3}
  - CELERY_SLOW_QUEUE_CONCURRENCY=${CELERY_SLOW_QUEUE_CONCURRENCY:-1}
  - DEFAULT_FILE_STORAGE
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_STORAGE_BUCKET_NAME
  - AWS_S3_CUSTOM_DOMAIN
  - AZURE_ACCOUNT_KEY
  - AZURE_ACCOUNT_NAME
  - AZURE_CONTAINER
  - AZURE_CUSTOM_DOMAIN
  - D3NET_OPENVINO=0
  - NVIDIA_VISIBLE_DEVICES=all
  - NVIDIA_DRIVER_CAPABILITIES=all
services:
  redis:
    image: redis:6.0-buster
    hostname: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: always
  nginx:
    image: jeffreyca/spleeter-web-nginx:${TAG:-latest}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - staticfiles:/webapp/staticfiles
    environment:
      - API_HOST=api
      - CERTBOT_EMAIL=. # Dummy email (overridden by https.yml)
      - CERTBOT_DOMAIN=.
    depends_on:
      - api
    restart: always
  api:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    volumes:
      - assets:/webapp/frontend/assets
      - sqlite-data:/webapp/sqlite
      - staticfiles:/webapp/staticfiles
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CPU_SEPARATION=0
      - ALLOW_ALL_HOSTS
      - APP_HOST
      - DEFAULT_FILE_STORAGE
      - ENABLE_CROSS_ORIGIN_HEADERS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_CUSTOM_DOMAIN
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
      - AZURE_CONTAINER
      - AZURE_CUSTOM_DOMAIN
      - YOUTUBE_API_KEY
    depends_on:
      - redis
      - frontend
    restart: always
  celery-fast:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    entrypoint: ./celery-fast-entrypoint.sh
    volumes:
      - celery-data:/webapp/celery
      - pretrained-models:/webapp/pretrained_models
      - sqlite-data:/webapp/sqlite
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment: *celery-env
    depends_on:
      - redis
    restart: always
  celery-slow:
    image: jeffreyca/spleeter-web-backend:${TAG:-latest}-gpu
    entrypoint: ./celery-slow-entrypoint.sh
    volumes:
      - celery-data:/webapp/celery
      - pretrained-models:/webapp/pretrained_models
      - sqlite-data:/webapp/sqlite
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment: *celery-env
    depends_on:
      - redis
    restart: always
  frontend:
    image: jeffreyca/spleeter-web-frontend:${TAG:-latest}
    volumes:
      - assets:/webapp/frontend/assets
    stdin_open: true
    tty: true
volumes:
  assets:
  celery-data:
  pretrained-models:
  redis-data:
  sqlite-data:
  staticfiles:
```
